### ISSUE TITLE
Subsetting always all bar codes instead of just twice the number of non-empty

### ISSUE THREAD

**Issue by insectopalo** [konopkalab/Ambient_RNA_In_Brain_snRNAseq#1]
I think the keepMax variable should correspond to the **minimum** between the number of non-empty droplets * 2 and the total number of droplets in the object. As it is now (max instead of min), it selects either all the bar codes in the object or even more than available.

https://github.com/konopkalab/Ambient_RNA_In_Brain_snRNAseq/blob/f954980b39fdac45f743056c754b14bd11890542/FUNCTIONS.R#L49

Hopefully I'm not wrong, I don't mean to waste your time.

**Comment by emrecaglayan** [comment]
Thank you for pointing this out and sorry for replying late. You are right, it should be minimum. I made a mistake while writing them as functions. It is corrected now.
